import { MetadataRoute } from 'next';
import { createStaticClient } from '@/lib/supabase/static-client';

// Must match layout.tsx metadataBase (seo.json) and robots.ts exactly.
const baseUrl = 'https://www.kritikasalonpatna.com';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const BUILD_NOW = new Date();
  const supabase = createStaticClient();

  // ── Static Pages ─────────────────────────────────────────────────────────
  const staticPages: MetadataRoute.Sitemap = [
    { url: baseUrl,               lastModified: BUILD_NOW, changeFrequency: 'daily',   priority: 1.0 },
    { url: `${baseUrl}/trending`, lastModified: BUILD_NOW, changeFrequency: 'daily',   priority: 0.9 },
    { url: `${baseUrl}/blog`,     lastModified: BUILD_NOW, changeFrequency: 'daily',   priority: 0.9 },
    { url: `${baseUrl}/nails`,    lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/makeup`,   lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/skin`,     lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/hair`,     lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/combo`,    lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/bridal`,   lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${baseUrl}/booking`,  lastModified: BUILD_NOW, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/about`,    lastModified: BUILD_NOW, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/contact`,  lastModified: BUILD_NOW, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/gallery`,  lastModified: BUILD_NOW, changeFrequency: 'weekly',  priority: 0.7 },
  ];

  // ── Location × Service pages: /{location-slug}/{service-slug} ──────────────
  // These are the real, live pages served by app/[first]/[second]/page.tsx,
  // generated by scripts/generate-junction.ts into service_location_pages.
  // Reading canonical_url straight from that table (rather than reconstructing
  // it here) guarantees the sitemap can never drift out of sync with what the
  // generator actually wrote and what the page actually serves.
  let locationServicePages: MetadataRoute.Sitemap = [];
  try {
    const { data: junctionPages } = await supabase
      .from('service_location_pages')
      .select('canonical_url, updated_at')
      .eq('is_active', true);

    locationServicePages = (junctionPages || [])
      .filter(p => p.canonical_url)
      .map(p => ({
        url: p.canonical_url!.startsWith('http')
          ? p.canonical_url!
          : `${baseUrl}${p.canonical_url!.startsWith('/') ? '' : '/'}${p.canonical_url}`,
        lastModified: p.updated_at ? new Date(p.updated_at) : BUILD_NOW,
        changeFrequency: 'weekly' as const,
        priority: 0.85,
      }));
  } catch (e) {
    console.error('Sitemap: service_location_pages fetch failed:', e);
  }

  // ── Category × Service pages: /{category}/{service-slug} ───────────────────
  // Also served by app/[first]/[second]/page.tsx, via the categoryPairs branch
  // of generateStaticParams (services.category + services.slug).
  let categoryServicePages: MetadataRoute.Sitemap = [];
  try {
    const { data: services } = await supabase
      .from('services')
      .select('slug, category, updated_at')
      .eq('is_active', true);

    categoryServicePages = (services || [])
      .filter(s => s.category && s.slug)
      .map(s => ({
        url: `${baseUrl}/${s.category.toLowerCase()}/${s.slug}`,
        lastModified: s.updated_at ? new Date(s.updated_at) : BUILD_NOW,
        changeFrequency: 'weekly' as const,
        priority: 0.8,
      }));
  } catch (e) {
    console.error('Sitemap: services (category pairs) fetch failed:', e);
  }

  // ── Blog posts ───────────────────────────────────────────────────────────
  let blogPages: MetadataRoute.Sitemap = [];
  try {
    const { data: posts } = await supabase
      .from('blog_posts')
      .select('slug, updated_at, published_at')
      .eq('status', 'published')
      .order('published_at', { ascending: false });

    blogPages = (posts || []).map(post => ({
      url: `${baseUrl}/blog/${post.slug}`,
      lastModified: new Date(post.updated_at || post.published_at),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    }));
  } catch (e) {
    console.error('Sitemap: blog_posts fetch failed:', e);
  }

  // ── Blog categories: /blog/category/[slug] ──────────────────────────────
  let categoryPages: MetadataRoute.Sitemap = [];
  try {
    const { data: blogCategories } = await supabase
      .from('categories')
      .select('slug, updated_at');

    categoryPages = (blogCategories || []).map(cat => ({
      url: `${baseUrl}/blog/category/${cat.slug}`,
      lastModified: new Date(cat.updated_at || BUILD_NOW),
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    }));
  } catch (e) {
    console.error('Sitemap: blog categories fetch failed:', e);
  }

  // ── Blog authors: /blog/author/[slug] ───────────────────────────────────
  let authorPages: MetadataRoute.Sitemap = [];
  try {
    const { data: authors } = await supabase
      .from('authors')
      .select('slug, updated_at');

    authorPages = (authors || []).map(author => ({
      url: `${baseUrl}/blog/author/${author.slug}`,
      lastModified: new Date(author.updated_at || BUILD_NOW),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }));
  } catch (e) {
    console.error('Sitemap: authors fetch failed:', e);
  }

  return [
    ...staticPages,
    ...locationServicePages,
    ...categoryServicePages,
    ...blogPages,
    ...categoryPages,
    ...authorPages,
  ];
}
